package com.appmetr.hercules.annotations.comparator;

public enum EntityComparatorType {
    ASCIITYPE, BOOLEANTYPE, BYTESTYPE, DATETYPE, DECIMALTYPE, FLOATTYPE, INTEGERTYPE, INT32TYPE,
    LEXICALUUIDTYPE, LOCALBYPARTITIONERTYPE, LONGTYPE, TIMEUUIDTYPE,
    UTF8TYPE, COMPOSITETYPE, DYNAMICCOMPOSITETYPE, UUIDTYPE, COUNTERTYPE, REVERSEDTYPE
}
